Use Fedora template as baseline

diff --git a/mageia.yaml b/mageia.yaml
--- a/mageia.yaml
+++ b/mageia.yaml
@@ -11,7 +11,7 @@ image:
 
 source:
   downloader: rootfs-http
-  url: file:///home/alex/Git/Mageia-LXC/mageia8.sqsh
+  url: file:///home/alex/IT/Mageia-LXC/Mageia8.sqfs
     #keys:
     #- 0xEDCA7A90
     #keyserver: http://pool.sks-keyservers.net
@@ -22,201 +22,366 @@ source:
 
 targets:
   lxc:
-    create_message: |-
+    create_message: |
       You just created a {{ image.description }} container.
-      No default root or user password are set by LXC.
-      Use: lxc-execute {{ image }}{{ release }} -- passwd root
-
     config:
-#      - type: all
-#        before: 5
-#        content: |-
-#          lxc.include = LXC_TEMPLATE_CONFIG/ubuntu.common.conf
-##
-#      - type: user
-#        before: 5
-#        content: |-
-#          lxc.include = LXC_TEMPLATE_CONFIG/ubuntu.userns.conf
-#
-      - type: all
-        after: 4
-        content: |-
-          lxc.include = LXC_TEMPLATE_CONFIG/common.conf
-#
-#      - type: user
-#        after: 4
-#        content: |-
-#          lxc.include = LXC_TEMPLATE_CONFIG/userns.conf
-#
-#      - type: all
-#        content: |-
-#          lxc.arch = {{ image.architecture_personality }}
-#  lxd:
-#    vm:
-#      size: 2147483648
-#      filesystem: ext4
+    - type: all
+      before: 5
+      content: |-
+        lxc.include = LXC_TEMPLATE_CONFIG/mageia.common.conf
 
-#files:
-#  - generator: dump
-#    path: /some/path
-#    content: |-
-#      here goes the content
-#    name: name
-#    mode: 0644
-#    gid: 1000
-#    uid: 1000
-#    template:
-#      properties:
-#        key: value
-#      when:
-#        - always
-#    templated: true
-#    releases:
-#      - a
-#      - b
-#    architectures:
-#      - x86_64
-#    variants:
-#      - default
-#
-#  - generator: hostname
-#    path: /etc/hostname
-#
-#  - generator: hosts
-#    path: /etc/hosts
-#
-#  - generator: remove
-#    path: /root/file
-#
-#  - generator: template
-#    name: foo
-#    content: |-
-#      Here goes the content
-#    template:
-#      properties:
-#        key: value
-#      when:
-#        - create
-#        - copy
+    - type: user
+      before: 5
+      content: |-
+        lxc.include = LXC_TEMPLATE_CONFIG/mageia.userns.conf
 
-          #  - generator: upstart-tty
-          #    path: /etc/init/lxc-tty.conf
+    - type: all
+      after: 4
+      content: |-
+        lxc.include = LXC_TEMPLATE_CONFIG/common.conf
 
-#  - generator: cloud-init
-#    name: user-data
-#    content: |-
-#      Here goes the user-data
-#
+    - type: user
+      after: 4
+      content: |-
+        lxc.include = LXC_TEMPLATE_CONFIG/userns.conf
+
+    - type: all
+      content: |-
+        lxc.arch = {{ image.architecture_kernel }}
+
+files:
+- path: /etc/default/grub
+  generator: dump
+  content: |-
+    # Set the recordfail timeout
+    GRUB_RECORDFAIL_TIMEOUT=0
+
+    # Do not wait on grub prompt
+    GRUB_TIMEOUT=0
+
+    # Set the default commandline
+    GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} console=tty1 console=ttyS0"
+
+    # Set the grub console type
+    GRUB_TERMINAL=console
+
+    # Disable os-prober
+    GRUB_DISABLE_OS_PROBER=true
+  types:
+  - vm
+
+- path: /etc/dracut.conf.d/lxd.conf
+  generator: dump
+  content: |-
+    add_drivers+=virtio_scsi
+  types:
+  - vm
+
+- generator: fstab
+  types:
+  - vm
+
+- path: /etc/machine-id
+  generator: dump
+
+- path: /etc/fstab
+  generator: dump
+  types:
+  - container
+
+- path: /var/lib/dbus/machine-id
+  generator: remove
+
+- path: /etc/hostname
+  generator: hostname
+
+- path: /etc/hosts
+  generator: hosts
+
+- name: eth0.network
+  path: /etc/systemd/network/eth0.network
+  generator: dump
+  content: |-
+    [Match]
+    Name=eth0
+
+    [Network]
+    DHCP=ipv4
+  variants:
+  - default
+  types:
+  - container
+
+- name: enp5s0.network
+  path: /etc/systemd/network/enp5s0.network
+  generator: dump
+  content: |-
+    [Match]
+    Name=enp5s0
+
+    [Network]
+    DHCP=ipv4
+  variants:
+  - default
+  types:
+  - vm
+
+- name: meta-data
+  generator: cloud-init
+  variants:
+  - cloud
+
+- name: network-config
+  generator: cloud-init
+  content: |-
+    {% if config_get("user.network-config", "") == "" %}version: 1
+    config:
+      - type: physical
+        name: {% if instance.type == "virtual-machine" %}enp5s0{% else %}eth0{% endif %}
+        subnets:
+          - type: {% if config_get("user.network_mode", "") == "link-local" %}manual{% else %}dhcp{% endif %}
+            control: auto
+          - type: dhcp6
+            control: auto{% else %}{{ config_get("user.network-config", "") }}{% endif %}
+  variants:
+  - cloud
+
+- name: user-data
+  generator: cloud-init
+  variants:
+  - cloud
+
+- name: vendor-data
+  generator: cloud-init
+  variants:
+  - cloud
+
+- generator: lxd-agent
+  types:
+  - vm
+
 packages:
   manager: dnf
-    #  custom_manager:
-#    clean:
-#      cmd: mgr
-#      flags:
-#        - clean
-#    install:
-#      cmd: mgr
-#      flags:
-#        - install
-#    remove:
-#      cmd: mgr
-#      flags:
-#        - remove
-#    refresh:
-#      cmd: mgr
-#      flags:
-#        - refresh
-#    update:
-#      cmd: mgr
-#      flags:
-#        - update
-#    flags:
-#      - --yes
 #  update: true
-#  cleanup: false
+#  cleanup: true
 #  sets:
-#    - packages:
-#        - gnupg
-#      action: install
-#      early: true
+#  - packages:
+#    - cpio
+#    - file
+#    - findutils
+#    - fipscheck
+#    - gettext
+#    - glibc-all-langpacks
+#    - hardlink
+#    - hostname
+#    - ipcalc
+#    - iproute
+#    - iproute-tc
+#    - iputils
+#    - kbd
+#    - kmod
+#    - openssh-clients
+#    - passwd
+#    - pigz
+#    - policycoreutils
+#    - procps-ng
+#    - sudo
+#    - systemd-udev
+#    - which
+#    - xz
+#    action: install
 #
-#    - packages:
-#        - vim
-#      action: install
-#      releases:
-#        - a
-#        - b
-#      architectures:
-#        - x86_64
-#      variants:
-#        - default
-#
-#    - packages:
-#        - lightdm
-#      action: install
-#      flags:
-#        - --no-install-recommends
-#
-#    - packages:
-#        - grub
-#      action: remove
-#
-#  repositories:
-#    - name: reponame
-#      url: |-
-#        deb http://archive.ubuntu.com/ubuntu {{ image.release }}-updates main restricted universe multiverse
-#      type: type
-#      key: 0xdeadbeaf
-#      releases:
-#        - a
-#        - b
-#      architectures:
-#        - x86_64
-#      variants:
-#        - default
-#
-actions:
-    - trigger: post-unpack
-      action: |-
-        #!/bin/sh
-        cat /etc/redhat-release
-        #echo -e "toorinlxc\ntoorinlxc" | passwd --stdin root
-#
-#  - trigger: post-files
-#    action: |-
-#       #!/bin/sh
-#       passwd root
-#
-#      do something after the files section has been processed
-#
-#  - trigger: post-update
-#    action: |-
-#      #!/bin/sh
-#
-#      do something after packages have been processed
-#
-#  - trigger: post-packages
-#    action: |-
-#      #!/bin/sh
-#
-#      do something after the packages section has been processed
-#
-#    releases:
-#      - a
-#      - b
-#    architectures:
-#      - x86_64
+#  - packages:
+#    - cloud-init
+#    - openssh-server
+#    action: install
 #    variants:
-#      - default
+#    - cloud
 #
-#mappings:
-#  architectures:
-#    a: b
-#    c: d
-#  architecture_map: debian
+#  - packages:
+#    - cloud-utils-growpart
+#    action: install
+#    types:
+#    - vm
+#    variants:
+#    - cloud
 #
-#environment:
-#  clear_defaults: true
-#  variables:
-#    - key: FOO
-#      value: bar
+#  - packages:
+#    - libsss_idmap
+#    - libsss_nss_idmap
+#    - sssd-client
+#    action: remove
+#
+#  - packages:
+#    - grub2-efi-x64
+#    action: install
+#    architectures:
+#    - x86_64
+#    types:
+#    - vm
+#
+#  - packages:
+#    - grub2-efi-aa64
+#    action: install
+#    architectures:
+#    - aarch64
+#    types:
+#    - vm
+#
+#  - packages:
+#    - kernel
+#    - shim
+#    - dracut
+#    action: install
+#    types:
+#    - vm
+
+actions:
+- trigger: post-unpack
+  action: |-
+    #!/bin/sh
+
+    set -eux
+
+    # Increase connection timeout
+    echo timeout=60 >> /etc/dnf/dnf.conf
+
+    # Let dnf find the fastest mirror
+    echo fastestmirror=True >> /etc/dnf/dnf.conf
+
+    # Backup all repo files
+    for repo in $(ls /etc/yum.repos.d/*.repo); do
+      cp "${repo}" "${repo}.bak"
+    done
+
+- trigger: post-unpack
+  action: |-
+    #!/bin/sh
+
+    set -eux
+
+    # Use baseurl instead of metalink to avoid networking issues
+    for repo in $(ls /etc/yum.repos.d/*.repo); do
+      grep -q '^#baseurl' "${repo}" || continue
+
+      sed -ri 's/^metalink=.*/#\0/g;s@^#(baseurl=)http://download.example/pub(.*)@\1https://mirror.csclub.uwaterloo.ca/\2@g' "${repo}"
+    done
+  architectures:
+  - aarch64
+  - armhfp
+  - x86_64
+
+- trigger: post-unpack
+  action: |-
+    #!/bin/sh
+
+    set -eux
+
+    # Use Fedora 38 GPG key to avoid package installation errors
+    for repo in $(ls /etc/yum.repos.d/*.repo); do
+      grep -q 'RPM-GPG-KEY-fedora-38' "${repo}" && continue
+
+      sed -ri 's#^gpgkey=.*#\0 file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-38-$basearch#g' "${repo}"
+    done
+  architectures:
+  - aarch64
+  - x86_64
+  releases:
+  - Rawhide
+
+- trigger: post-unpack
+  action: |-
+    #!/bin/sh
+
+    set -eux
+
+    # Use baseurl instead of metalink to avoid networking issues
+    for repo in $(ls /etc/yum.repos.d/*.repo); do
+      grep -q '^#baseurl' "${repo}" || continue
+
+      sed -ri 's/^metalink=.*/#\0/g;s@^#(baseurl=)http://download.example/pub/fedora/linux(.*)@\1https://muug.ca/mirror/fedora-secondary\2@g' "${repo}"
+    done
+  architectures:
+  - ppc64le
+  - s390x
+
+- trigger: post-packages
+  action: |-
+    #!/bin/sh
+    umount -l /etc/resolv.conf || true
+    rm /etc/resolv.conf
+    ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
+    systemctl enable systemd-resolved
+    cp -R /etc/skel/.bash* /root/
+
+- trigger: post-packages
+  action: |-
+    #!/bin/sh
+    systemctl enable systemd-networkd
+  variants:
+  - default
+
+- trigger: post-packages
+  action: |-
+    #!/bin/sh
+    systemctl enable systemd-networkd
+  variants:
+  - cloud
+
+- trigger: post-packages
+  action: |-
+    #!/bin/sh
+    systemctl enable cloud-init
+    systemctl enable cloud-config
+    systemctl enable cloud-final
+  variants:
+  - cloud
+
+- trigger: post-unpack
+  action: |-
+    #!/bin/sh
+    # Generate machine-id in order for the kernel stuff to be configured properly
+    systemd-machine-id-setup
+  types:
+  - vm
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    # Remove the "Container Image" string as this is going to be am VM
+    sed -i 's/[ ]*(Container Image)//;/^VARIANT/d' /etc/os-release
+
+    target=/boot/efi/EFI/fedora/grub.cfg
+    grub2-mkconfig -o "${target}"
+    sed -i "s#root=[^ ]*#root=/dev/sda2#g" "${target}"
+
+    sed -Eri "s#^(linux|initrd) .+/overlay/#\1 /#g" /boot/loader/entries/*
+    sed -ri 's#^options .+#options $kernelopts#g' /boot/loader/entries/*
+
+    # Regenerate initramfs
+    kver=$(ls /boot/initramfs-*.img | sed -r 's#.*initramfs-(.+)\.img#\1#')
+    dracut --kver "${kver}" -f
+
+    # Unmask all masked unit files
+    for f in $(find /etc/systemd/system -type l); do
+      [ "$(readlink ${f})" = "/dev/null" ] && rm "${f}"
+    done
+
+    # Wipe grub environment
+    rm -f /boot/efi/EFI/fedora/grubenv
+
+    exit 0
+  types:
+  - vm
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    # Restore repos
+    for repo in $(ls /etc/yum.repos.d/*.bak); do
+      mv "${repo}" ${repo%.*}
+    done
